### ISSUE TITLE
Fails to build with Boost 1.74

### ISSUE THREAD

**Issue by sebastic** [Icinga/icinga2#8493]
As reported by Anton Gladky in [Debian Bug #975416](https://bugs.debian.org/975416):
> it was discovered that your package failed to build against boost_1.74. Logs can be found here [1].
> Most relevant part is probably this:
>
> ```
> In file included from /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/lib/base/base_unity.cpp:74:
> /<<PKGBUILDDIR>>/lib/base/utility.cpp: In static member function ‘static void icinga::Utility::CopyFile(const icinga::String&, const icinga::String&)’:
> /<<PKGBUILDDIR>>/lib/base/utility.cpp:728:100: error: ‘fs::copy_option’ has not been declared
>   728 |  fs::copy_file(fs::path(source.Begin(), source.End()), fs::path(target.Begin(), target.End()), fs::copy_option::overwrite_if_exists);
> ```
>
> It is planned to push boost_1.74 as the default version in Debian/Bullseye.
>
> [1] http://qa-logs.debian.net/2020/10/27-boost/boost/icinga2_2.12.1-1_unstable_boost.log

**Comment by sebastic** [comment]
Seems to be a duplicate of #8185.
