### ISSUE TITLE
Build fails with boost 1.72.0: error: ‘begin’ is not a member of ‘boost’

### ISSUE THREAD

**Issue by sbraz** [Icinga/icinga2#7730]
Hi,
The latest git master fails to build with boost 1.72.0. The build stops at
```
cd /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999_build/lib/base && /usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++ -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -I/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/third-party/nlohmann_json -I/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/third-party/utf8cpp/source -I/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999 -I/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib -I/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999_build -I/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999_build/lib -I/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/third-party/execvpe -I/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/third-party/mmatch -I/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/third-party/socketpair   -DNDEBUG -O2 -pipe -march=native -lpthread  -pthread -Winvalid-pch -std=c++0x   -o CMakeFiles/base.dir/io-engine.cpp.o -c /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp
```
With:
<details>
```
In file included from /usr/include/boost/coroutine/coroutine.hpp:10,
                 from /usr/include/boost/coroutine/all.hpp:11,
                 from /usr/include/boost/asio/spawn.hpp:19,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.hpp:16,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:4:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp: In function ‘typename boost::coroutines::pull_coroutine<R>::iterator boost::coroutines::begin(boost::coroutines::pull_coroutine<Arg>&)’:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2364:17: error: ‘begin’ is not a member of ‘boost’
 2364 | { return boost::begin( c); }
      |                 ^~~~~
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2364:17: note: suggested alternatives:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/string:54,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/stdexcept:39,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/i2-base.hpp:69,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:6,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/range_access.h:87:5: note:   ‘std::begin’
   87 |     begin(_Tp (&__arr)[_Nm])
      |     ^~~~~
In file included from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999_build/lib/base/configobject-ti.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/configobject.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:12,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/array.hpp:110:17: note:   ‘icinga::begin’
  110 | Array::Iterator begin(const Array::Ptr& x);
      |                 ^~~~~
In file included from /usr/include/boost/mpl/begin_end.hpp:17,
                 from /usr/include/boost/mpl/iter_fold.hpp:18,
                 from /usr/include/boost/variant/detail/initializer.hpp:28,
                 from /usr/include/boost/variant/variant.hpp:30,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/value.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/dictionary.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:11,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/include/boost/mpl/begin_end_fwd.hpp:22:38: note:   ‘boost::mpl::begin’
   22 | template< typename Sequence > struct begin;
      |                                      ^~~~~
In file included from /usr/include/boost/coroutine/coroutine.hpp:10,
                 from /usr/include/boost/coroutine/all.hpp:11,
                 from /usr/include/boost/asio/spawn.hpp:19,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.hpp:16,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:4:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2363:1: note:   ‘boost::coroutines::begin’
 2363 | begin( pull_coroutine< R > & c)
      | ^~~~~
/usr/include/boost/coroutine/asymmetric_coroutine.hpp: In function ‘typename boost::coroutines::pull_coroutine<R>::const_iterator boost::coroutines::begin(const boost::coroutines::pull_coroutine<Arg>&)’:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2369:17: error: ‘begin’ is not a member of ‘boost’
 2369 | { return boost::begin( c); }
      |                 ^~~~~
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2369:17: note: suggested alternatives:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/string:54,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/stdexcept:39,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/i2-base.hpp:69,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:6,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/range_access.h:87:5: note:   ‘std::begin’
   87 |     begin(_Tp (&__arr)[_Nm])
      |     ^~~~~
In file included from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999_build/lib/base/configobject-ti.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/configobject.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:12,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/array.hpp:110:17: note:   ‘icinga::begin’
  110 | Array::Iterator begin(const Array::Ptr& x);
      |                 ^~~~~
In file included from /usr/include/boost/mpl/begin_end.hpp:17,
                 from /usr/include/boost/mpl/iter_fold.hpp:18,
                 from /usr/include/boost/variant/detail/initializer.hpp:28,
                 from /usr/include/boost/variant/variant.hpp:30,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/value.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/dictionary.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:11,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/include/boost/mpl/begin_end_fwd.hpp:22:38: note:   ‘boost::mpl::begin’
   22 | template< typename Sequence > struct begin;
      |                                      ^~~~~
In file included from /usr/include/boost/coroutine/coroutine.hpp:10,
                 from /usr/include/boost/coroutine/all.hpp:11,
                 from /usr/include/boost/asio/spawn.hpp:19,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.hpp:16,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:4:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2368:1: note:   ‘boost::coroutines::begin’
 2368 | begin( pull_coroutine< R > const& c)
      | ^~~~~
/usr/include/boost/coroutine/asymmetric_coroutine.hpp: In function ‘typename boost::coroutines::pull_coroutine<R>::iterator boost::coroutines::end(boost::coroutines::pull_coroutine<Arg>&)’:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2374:17: error: ‘end’ is not a member of ‘boost’
 2374 | { return boost::end( c); }
      |                 ^~~
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2374:17: note: suggested alternatives:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/string:54,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/stdexcept:39,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/i2-base.hpp:69,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:6,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/range_access.h:97:5: note:   ‘std::end’
   97 |     end(_Tp (&__arr)[_Nm])
      |     ^~~
In file included from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999_build/lib/base/configobject-ti.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/configobject.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:12,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/array.hpp:111:17: note:   ‘icinga::end’
  111 | Array::Iterator end(const Array::Ptr& x);
      |                 ^~~
In file included from /usr/include/boost/mpl/begin_end.hpp:17,
                 from /usr/include/boost/mpl/iter_fold.hpp:18,
                 from /usr/include/boost/variant/detail/initializer.hpp:28,
                 from /usr/include/boost/variant/variant.hpp:30,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/value.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/dictionary.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:11,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/include/boost/mpl/begin_end_fwd.hpp:23:38: note:   ‘boost::mpl::end’
   23 | template< typename Sequence > struct end;
      |                                      ^~~
In file included from /usr/include/boost/coroutine/coroutine.hpp:10,
                 from /usr/include/boost/coroutine/all.hpp:11,
                 from /usr/include/boost/asio/spawn.hpp:19,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.hpp:16,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:4:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2373:1: note:   ‘boost::coroutines::end’
 2373 | end( pull_coroutine< R > & c)
      | ^~~
/usr/include/boost/coroutine/asymmetric_coroutine.hpp: In function ‘typename boost::coroutines::pull_coroutine<R>::const_iterator boost::coroutines::end(const boost::coroutines::pull_coroutine<Arg>&)’:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2379:17: error: ‘end’ is not a member of ‘boost’
 2379 | { return boost::end( c); }
      |                 ^~~
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2379:17: note: suggested alternatives:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/string:54,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/stdexcept:39,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/i2-base.hpp:69,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:6,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/range_access.h:97:5: note:   ‘std::end’
   97 |     end(_Tp (&__arr)[_Nm])
      |     ^~~
In file included from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999_build/lib/base/configobject-ti.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/configobject.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:12,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/array.hpp:111:17: note:   ‘icinga::end’
  111 | Array::Iterator end(const Array::Ptr& x);
      |                 ^~~
In file included from /usr/include/boost/mpl/begin_end.hpp:17,
                 from /usr/include/boost/mpl/iter_fold.hpp:18,
                 from /usr/include/boost/variant/detail/initializer.hpp:28,
                 from /usr/include/boost/variant/variant.hpp:30,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/value.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/dictionary.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:11,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/include/boost/mpl/begin_end_fwd.hpp:23:38: note:   ‘boost::mpl::end’
   23 | template< typename Sequence > struct end;
      |                                      ^~~
In file included from /usr/include/boost/coroutine/coroutine.hpp:10,
                 from /usr/include/boost/coroutine/all.hpp:11,
                 from /usr/include/boost/asio/spawn.hpp:19,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.hpp:16,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:4:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2378:1: note:   ‘boost::coroutines::end’
 2378 | end( pull_coroutine< R > const& c)
      | ^~~
/usr/include/boost/coroutine/asymmetric_coroutine.hpp: In function ‘typename boost::coroutines::push_coroutine<Arg>::iterator boost::coroutines::begin(boost::coroutines::push_coroutine<R>&)’:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2384:17: error: ‘begin’ is not a member of ‘boost’
 2384 | { return boost::begin( c); }
      |                 ^~~~~
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2384:17: note: suggested alternatives:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/string:54,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/stdexcept:39,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/i2-base.hpp:69,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:6,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/range_access.h:87:5: note:   ‘std::begin’
   87 |     begin(_Tp (&__arr)[_Nm])
      |     ^~~~~
In file included from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999_build/lib/base/configobject-ti.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/configobject.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:12,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/array.hpp:110:17: note:   ‘icinga::begin’
  110 | Array::Iterator begin(const Array::Ptr& x);
      |                 ^~~~~
In file included from /usr/include/boost/mpl/begin_end.hpp:17,
                 from /usr/include/boost/mpl/iter_fold.hpp:18,
                 from /usr/include/boost/variant/detail/initializer.hpp:28,
                 from /usr/include/boost/variant/variant.hpp:30,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/value.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/dictionary.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:11,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/include/boost/mpl/begin_end_fwd.hpp:22:38: note:   ‘boost::mpl::begin’
   22 | template< typename Sequence > struct begin;
      |                                      ^~~~~
In file included from /usr/include/boost/coroutine/coroutine.hpp:10,
                 from /usr/include/boost/coroutine/all.hpp:11,
                 from /usr/include/boost/asio/spawn.hpp:19,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.hpp:16,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:4:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2383:1: note:   ‘boost::coroutines::begin’
 2383 | begin( push_coroutine< R > & c)
      | ^~~~~
/usr/include/boost/coroutine/asymmetric_coroutine.hpp: In function ‘typename boost::coroutines::push_coroutine<Arg>::iterator boost::coroutines::end(boost::coroutines::push_coroutine<R>&)’:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2389:17: error: ‘end’ is not a member of ‘boost’
 2389 | { return boost::end( c); }
      |                 ^~~
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2389:17: note: suggested alternatives:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/string:54,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/stdexcept:39,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/i2-base.hpp:69,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:6,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/range_access.h:97:5: note:   ‘std::end’
   97 |     end(_Tp (&__arr)[_Nm])
      |     ^~~
In file included from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999_build/lib/base/configobject-ti.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/configobject.hpp:7,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:12,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/array.hpp:111:17: note:   ‘icinga::end’
  111 | Array::Iterator end(const Array::Ptr& x);
      |                 ^~~
In file included from /usr/include/boost/mpl/begin_end.hpp:17,
                 from /usr/include/boost/mpl/iter_fold.hpp:18,
                 from /usr/include/boost/variant/detail/initializer.hpp:28,
                 from /usr/include/boost/variant/variant.hpp:30,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/value.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/dictionary.hpp:8,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/exception.hpp:11,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:3:
/usr/include/boost/mpl/begin_end_fwd.hpp:23:38: note:   ‘boost::mpl::end’
   23 | template< typename Sequence > struct end;
      |                                      ^~~
In file included from /usr/include/boost/coroutine/coroutine.hpp:10,
                 from /usr/include/boost/coroutine/all.hpp:11,
                 from /usr/include/boost/asio/spawn.hpp:19,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.hpp:16,
                 from /var/tmp/portage/net-analyzer/icinga2-9999/work/icinga2-9999/lib/base/io-engine.cpp:4:
/usr/include/boost/coroutine/asymmetric_coroutine.hpp:2388:1: note:   ‘boost::coroutines::end’
 2388 | end( push_coroutine< R > & c)
      | ^~~
```
</details>

Gentoo bug report: https://bugs.gentoo.org/704128

**Comment by dnsmichi** [comment]
That's a bug in Boost 1.72 itself, see the the `boost::begin` error. I'd say that this is the same as listed in the `Known Issues` section here: https://www.boost.org/users/history/version_1_72_0.html

https://www.boost.org/patches/1_72_0/0001-revert-cease-dependence-on-range.patch

**Comment by sbraz** [comment]
Thanks, I couldn't understand why there was an error _within_ boost's own files. I'll try that patch.
