### ISSUE TITLE
incinga2: Fails to build with Boost 1.67.0

### ISSUE THREAD

**Issue by thardeck** [Icinga/icinga2#6232]
The new Boost library 1.67.0 has been released and unfortunately Icinga2 fails to build with it.

[Here](https://build.opensuse.org/package/live_build_log/home:adamm:boost_test/icinga2/openSUSE_Tumbleweed/x86_64) is the output of a package build against openSUSE Tumbleweed with the new boost library:

> [   95s] /home/abuild/rpmbuild/BUILD/icinga2-2.8.2/lib/base/timer.cpp: In static member function 'static void icinga::Timer::TimerThreadProc()':
> [   95s] /home/abuild/rpmbuild/BUILD/icinga2-2.8.2/lib/base/timer.cpp:269:74: error: no matching function for call to 'boost::date_time::subsecond_duration<boost::posix_time::time_duration, 1000>::subsecond_duration(double)'
> [   95s]     l_TimerCV.timed_wait(lock, boost::posix_time::milliseconds(wait * 1000));
> [   95s]                                                                           ^

The cause of this is change in Boost:DateTime that no longer accepts non-integer types. In the past, these types were implicitly cast down to integer values. Now this requires explicit cast.

https://svn.boost.org/trac10/ticket/11168

## Expected Behavior
Icinga 2 builds without issues against the latest Boost library 1.67.0.

## Current Behavior
Icinga 2 does not build build against the latest Boost library 1.67.0.

## Possible Solution
Use the integer type for all date values.

## Steps to Reproduce
1. Build Icinga2 against latest Boost library 1.67.0

## Context
Build Icinga 2 on openSUSE Tumbleweed with the latest boost library 1.67.0.

## Your Environment
* Icinga version: 2.8.2
* openSUSE Tumbleweed 20180410

The issue was reported on the openSUSE bug tracker: https://bugzilla.suse.com/show_bug.cgi?id=1089808

**Comment by dnsmichi** [comment]
That's already fixed with #6230.
