### PR TITLE
Fix build on Mac with -DICINGA2_UNITY_BUILD=OFF -DICINGA2_WITH_LIVESTATUS=ON

### PR DESCRIPTION
**Pull request by Al2Klimov**
error: no matching function for call to 'intrusive_ptr_release'
...
candidate function not viable: cannot convert argument of incomplete type 'icinga::Notification *' to 'Object *' for 1st argument
void intrusive_ptr_release(Object *object);

## Edit

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
7a0796061a0b38b93dc1717fd25a57cec992509c
10bde2075aa8017699f3738e9f01af2ac30e7ad1
4d3b1709fdb4cfefeb7e93718032b4905cd947b4
73e0d6e61baa5dfa88bba61bfe4235042aa06b38
e1c6c9eb19919ad085405592185a3854e9dcf435
2ad0a4b8c3852ad937fec9fc85780230257c821e
We cannot bisect more!

### CODE REVIEW

File: lib/icinga/notification.hpp [hunk 1]
```diff
@@ -55,6 +55,7 @@ class ApplyRule;
 struct ScriptFrame;
 class Host;
 class Service;
+class UserGroup;
```
Comment (yhabteab) [inline lib/icinga/notification.hpp:58]: This forward declaration isn't necessary!

Comment (Al2Klimov) [reply lib/icinga/notification.hpp:58]: Doesn't work on my machine:

```
[36/98] /Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -D_GNU_SOURCE -I/Users/aklimov/NET/WS/boost_1_69_0 -I/Users/aklimov/NET/WS/openssl/include -I/Users/aklimov/NET/WS/icinga2/third-party/nlohmann_json -I/Users/aklimov/NET/WS/icinga2/third-party/utf8cpp/source -I/Users/aklimov/NET/WS/icinga2 -I/Users/aklimov/NET/WS/icinga2/lib -I/Users/aklimov/NET/WS/icinga2/build-clion -I/Users/aklimov/NET/WS/icinga2/build-clion/lib -DI2_DEBUG=1 -Wall -Wextra -Wno-enum-constexpr-conversion -w -Qunused-arguments -fcolor-diagnostics -fno-limit-debug-info -pthread -Winvalid-pch -g -DI2_DEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk -mmacosx-version-min=14.7 -fcolor-diagnostics -MD -MT lib/icinga/CMakeFiles/icinga.dir/user.cpp.o -MF lib/icinga/CMakeFiles/icinga.dir/user.cpp.o.d -o lib/icinga/CMakeFiles/icinga.dir/user.cpp.o -c /Users/aklimov/NET/WS/icinga2/lib/icinga/user.cpp
FAILED: lib/icinga/CMakeFiles/icinga.dir/user.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -D_GNU_SOURCE -I/Users/aklimov/NET/WS/boost_1_69_0 -I/Users/aklimov/NET/WS/openssl/include -I/Users/aklimov/NET/WS/icinga2/third-party/nlohmann_json -I/Users/aklimov/NET/WS/icinga2/third-party/utf8cpp/source -I/Users/aklimov/NET/WS/icinga2 -I/Users/aklimov/NET/WS/icinga2/lib -I/Users/aklimov/NET/WS/icinga2/build-clion -I/Users/aklimov/NET/WS/icinga2/build-clion/lib -DI2_DEBUG=1 -Wall -Wextra -Wno-enum-constexpr-conversion -w -Qunused-arguments -fcolor-diagnostics -fno-limit-debug-info -pthread -Winvalid-pch -g -DI2_DEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk -mmacosx-version-min=14.7 -fcolor-diagnostics -MD -MT lib/icinga/CMakeFiles/icinga.dir/user.cpp.o -MF lib/icinga/CMakeFiles/icinga.dir/user.cpp.o.d -o lib/icinga/CMakeFiles/icinga.dir/user.cpp.o -c /Users/aklimov/NET/WS/icinga2/lib/icinga/user.cpp
In file included from /Users/aklimov/NET/WS/icinga2/lib/icinga/user.cpp:4:
In file included from /Users/aklimov/NET/WS/icinga2/build-clion/lib/icinga/user-ti.cpp:17:
In file included from /Users/aklimov/NET/WS/icinga2/lib/icinga/usergroup.hpp:7:
/Users/aklimov/NET/WS/icinga2/lib/icinga/notification.hpp:77:25: error: use of undeclared identifier 'UserGroup'
   77 |         std::set<intrusive_ptr<UserGroup>> GetUserGroups() const;
      |                                ^
1 error generated.
[37/98] /Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -D_GNU_SOURCE -I/Users/aklimov/NET/WS/boost_1_69_0 -I/Users/aklimov/NET/WS/openssl/include -I/Users/aklimov/NET/WS/icinga2/third-party/nlohmann_json -I/Users/aklimov/NET/WS/icinga2/third-party/utf8cpp/source -I/Users/aklimov/NET/WS/icinga2 -I/Users/aklimov/NET/WS/icinga2/lib -I/Users/aklimov/NET/WS/icinga2/build-clion -I/Users/aklimov/NET/WS/icinga2/build-clion/lib -DI2_DEBUG=1 -Wall -Wextra -Wno-enum-constexpr-conversion -w -Qunused-arguments -fcolor-diagnostics -fno-limit-debug-info -pthread -Winvalid-pch -g -DI2_DEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk -mmacosx-version-min=14.7 -fcolor-diagnostics -MD -MT lib/icinga/CMakeFiles/icinga.dir/scheduleddowntime.cpp.o -MF lib/icinga/CMakeFiles/icinga.dir/scheduleddowntime.cpp.o.d -o lib/icinga/CMakeFiles/icinga.dir/scheduleddowntime.cpp.o -c /Users/aklimov/NET/WS/icinga2/lib/icinga/scheduleddowntime.cpp
[38/98] /Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -D_GNU_SOURCE -I/Users/aklimov/NET/WS/boost_1_69_0 -I/Users/aklimov/NET/WS/openssl/include -I/Users/aklimov/NET/WS/icinga2/third-party/nlohmann_json -I/Users/aklimov/NET/WS/icinga2/third-party/utf8cpp/source -I/Users/aklimov/NET/WS/icinga2 -I/Users/aklimov/NET/WS/icinga2/lib -I/Users/aklimov/NET/WS/icinga2/build-clion -I/Users/aklimov/NET/WS/icinga2/build-clion/lib -DI2_DEBUG=1 -Wall -Wextra -Wno-enum-constexpr-conversion -w -Qunused-arguments -fcolor-diagnostics -fno-limit-debug-info -pthread -Winvalid-pch -g -DI2_DEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk -mmacosx-version-min=14.7 -fcolor-diagnostics -MD -MT lib/icinga/CMakeFiles/icinga.dir/servicegroup.cpp.o -MF lib/icinga/CMakeFiles/icinga.dir/servicegroup.cpp.o.d -o lib/icinga/CMakeFiles/icinga.dir/servicegroup.cpp.o -c /Users/aklimov/NET/WS/icinga2/lib/icinga/servicegroup.cpp
[39/98] /Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -D_GNU_SOURCE -I/Users/aklimov/NET/WS/boost_1_69_0 -I/Users/aklimov/NET/WS/openssl/include -I/Users/aklimov/NET/WS/icinga2/third-party/nlohmann_json -I/Users/aklimov/NET/WS/icinga2/third-party/utf8cpp/source -I/Users/aklimov/NET/WS/icinga2 -I/Users/aklimov/NET/WS/icinga2/lib -I/Users/aklimov/NET/WS/icinga2/build-clion -I/Users/aklimov/NET/WS/icinga2/build-clion/lib -DI2_DEBUG=1 -Wall -Wextra -Wno-enum-constexpr-conversion -w -Qunused-arguments -fcolor-diagnostics -fno-limit-debug-info -pthread -Winvalid-pch -g -DI2_DEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk -mmacosx-version-min=14.7 -fcolor-diagnostics -MD -MT lib/icinga/CMakeFiles/icinga.dir/service.cpp.o -MF lib/icinga/CMakeFiles/icinga.dir/service.cpp.o.d -o lib/icinga/CMakeFiles/icinga.dir/service.cpp.o -c /Users/aklimov/NET/WS/icinga2/lib/icinga/service.cpp
[40/98] /Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -D_GNU_SOURCE -I/Users/aklimov/NET/WS/boost_1_69_0 -I/Users/aklimov/NET/WS/openssl/include -I/Users/aklimov/NET/WS/icinga2/third-party/nlohmann_json -I/Users/aklimov/NET/WS/icinga2/third-party/utf8cpp/source -I/Users/aklimov/NET/WS/icinga2 -I/Users/aklimov/NET/WS/icinga2/lib -I/Users/aklimov/NET/WS/icinga2/build-clion -I/Users/aklimov/NET/WS/icinga2/build-clion/lib -DI2_DEBUG=1 -Wall -Wextra -Wno-enum-constexpr-conversion -w -Qunused-arguments -fcolor-diagnostics -fno-limit-debug-info -pthread -Winvalid-pch -g -DI2_DEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk -mmacosx-version-min=14.7 -fcolor-diagnostics -MD -MT lib/icinga/CMakeFiles/icinga.dir/usergroup.cpp.o -MF lib/icinga/CMakeFiles/icinga.dir/usergroup.cpp.o.d -o lib/icinga/CMakeFiles/icinga.dir/usergroup.cpp.o -c /Users/aklimov/NET/WS/icinga2/lib/icinga/usergroup.cpp
FAILED: lib/icinga/CMakeFiles/icinga.dir/usergroup.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -D_GNU_SOURCE -I/Users/aklimov/NET/WS/boost_1_69_0 -I/Users/aklimov/NET/WS/openssl/include -I/Users/aklimov/NET/WS/icinga2/third-party/nlohmann_json -I/Users/aklimov/NET/WS/icinga2/third-party/utf8cpp/source -I/Users/aklimov/NET/WS/icinga2 -I/Users/aklimov/NET/WS/icinga2/lib -I/Users/aklimov/NET/WS/icinga2/build-clion -I/Users/aklimov/NET/WS/icinga2/build-clion/lib -DI2_DEBUG=1 -Wall -Wextra -Wno-enum-constexpr-conversion -w -Qunused-arguments -fcolor-diagnostics -fno-limit-debug-info -pthread -Winvalid-pch -g -DI2_DEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk -mmacosx-version-min=14.7 -fcolor-diagnostics -MD -MT lib/icinga/CMakeFiles/icinga.dir/usergroup.cpp.o -MF lib/icinga/CMakeFiles/icinga.dir/usergroup.cpp.o.d -o lib/icinga/CMakeFiles/icinga.dir/usergroup.cpp.o -c /Users/aklimov/NET/WS/icinga2/lib/icinga/usergroup.cpp
In file included from /Users/aklimov/NET/WS/icinga2/lib/icinga/usergroup.cpp:3:
In file included from /Users/aklimov/NET/WS/icinga2/lib/icinga/usergroup.hpp:7:
/Users/aklimov/NET/WS/icinga2/lib/icinga/notification.hpp:77:25: error: use of undeclared identifier 'UserGroup'
   77 |         std::set<intrusive_ptr<UserGroup>> GetUserGroups() const;
      |                                ^
1 error generated.
[41/98] /Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -D_GNU_SOURCE -I/Users/aklimov/NET/WS/boost_1_69_0 -I/Users/aklimov/NET/WS/openssl/include -I/Users/aklimov/NET/WS/icinga2/third-party/nlohmann_json -I/Users/aklimov/NET/WS/icinga2/third-party/utf8cpp/source -I/Users/aklimov/NET/WS/icinga2 -I/Users/aklimov/NET/WS/icinga2/lib -I/Users/aklimov/NET/WS/icinga2/build-clion -I/Users/aklimov/NET/WS/icinga2/build-clion/lib -DI2_DEBUG=1 -Wall -Wextra -Wno-enum-constexpr-conversion -w -Qunused-arguments -fcolor-diagnostics -fno-limit-debug-info -pthread -Winvalid-pch -g -DI2_DEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk -mmacosx-version-min=14.7 -fcolor-diagnostics -MD -MT lib/cli/CMakeFiles/cli.dir/pkiverifycommand.cpp.o -MF lib/cli/CMakeFiles/cli.dir/pkiverifycommand.cpp.o.d -o lib/cli/CMakeFiles/cli.dir/pkiverifycommand.cpp.o -c /Users/aklimov/NET/WS/icinga2/lib/cli/pkiverifycommand.cpp
[42/98] /Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -D_GNU_SOURCE -I/Users/aklimov/NET/WS/boost_1_69_0 -I/Users/aklimov/NET/WS/openssl/include -I/Users/aklimov/NET/WS/icinga2/third-party/nlohmann_json -I/Users/aklimov/NET/WS/icinga2/third-party/utf8cpp/source -I/Users/aklimov/NET/WS/icinga2 -I/Users/aklimov/NET/WS/icinga2/lib -I/Users/aklimov/NET/WS/icinga2/build-clion -I/Users/aklimov/NET/WS/icinga2/build-clion/lib -DI2_DEBUG=1 -Wall -Wextra -Wno-enum-constexpr-conversion -w -Qunused-arguments -fcolor-diagnostics -fno-limit-debug-info -pthread -Winvalid-pch -g -DI2_DEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk -mmacosx-version-min=14.7 -fcolor-diagnostics -MD -MT lib/cli/CMakeFiles/cli.dir/daemonutility.cpp.o -MF lib/cli/CMakeFiles/cli.dir/daemonutility.cpp.o.d -o lib/cli/CMakeFiles/cli.dir/daemonutility.cpp.o -c /Users/aklimov/NET/WS/icinga2/lib/cli/daemonutility.cpp
ninja: build stopped: subcommand failed.
```

**Comment by yhabteab** [comment]
Pls. rebase!
