### ISSUE TITLE
[dev.icinga.com #12307] Windows build broken since ref 11292

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4432]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12307

**Created by TheFlyingCorpse on 2016-08-03 23:24:35 +00:00**

Assignee: _gbeutner_
Status: _Resolved_  (closed on _2016-08-04 04:52:06 +00:00_)
Target Version: _2.5.0_
Last Update: _2016-08-04 04:52:06 +00:00 (in Redmine)_

    Icinga Version: 2.4.10-master
    Backport?: Not yet backported
    Include in Changelog: 0

---

Refs [\#11292](https://dev.icinga.com/issues/11292)

Since this commit, I am getting the following error when trying to compile Icinga2:

    "C:\msvc14\icinga2\build10\lib\remote\remote.vcxproj" (default target) (13) ->
     (ClCompile target) ->  C:\msvc14\icinga2\lib\remote/apilistener.cpp(1184): error C2723: 'icinga::ApiListener::ValidateTlsProtocolmin': 'override' specifier illegal on function definition [C:\msvc14\icinga2\build10\lib\remote\remote.vcxproj]

Reverting this commit solves the issue.
