### ISSUE TITLE
Graphite-web does not work after update to 2.6.2.

### ISSUE THREAD

**Issue by Kulturserver** [Icinga/icinga2#7070]
We've installed the latest versions of icinga2 and graphite-web from the debian 9 backports. After that we weren't able to access the graphs of graphite-web anymore. The following error is shown:

[wsgi:error] [pid 9729] [remote
2001:16b8:4009:1e00:b6b5:2fff:fece:5239:33630] ImportError: cannot import name
smart_text

Anybody got a hint what might be the problem? Thanks!

We use the following:
- Debian 9.8
- python 2.7.13 & 3.5.3
- Graphite-web: 1.0.2
- python-django: 1.10.7
- python-whisper: 1.0.2

**Comment by dnsmichi** [comment]
This isn't Icinga 2 related, please ask such questions on https://community.icinga.com :)
